package com.codereviewer.utils;

import com.codereviewer.model.codeIssue;

import java.util.List;

public final class PromptBuilder {

    private PromptBuilder() {
    }

    /**
     * Builds the prompt for the AI code reviewer.
     *
     * @param sourceCode   Java source code being reviewed
     * @param staticIssues findings generated by static analyzers
     * @return complete AI review prompt
     */
    public static String build(
            String sourceCode,
            List<codeIssue> staticIssues) {

        StringBuilder prompt =
                new StringBuilder();

        prompt.append(
                "You are a senior Java code reviewer.\n"
        );

        prompt.append(
                "Review the Java code below. "
        );

        prompt.append(
                "Focus on correctness, security, "
        );

        prompt.append(
                "maintainability, performance and clean code.\n"
        );

        prompt.append(
                "Do not invent issues. Give actionable suggestions.\n\n"
        );

        prompt.append(
                "STATIC ANALYSIS FINDINGS:\n"
        );

        /*
         * Check whether static analysis found any issues.
         */
        if (staticIssues == null || staticIssues.isEmpty()) {

            prompt.append(
                    "No static-analysis findings.\n"
            );

        } else {

            /*
             * Add every static-analysis issue to the prompt.
             */
            for (codeIssue issue : staticIssues) {

                prompt.append("- [")
                        .append(issue.getSeverity())
                        .append("] ")
                        .append(issue.getRule())
                        .append(" at line ")
                        .append(issue.getLine())
                        .append(": ")
                        .append(issue.getMessage())
                        .append("\n");
            }
        }

        /*
         * Add the Java source code.
         */
        prompt.append(
                "\nJAVA SOURCE:\n```java\n"
        );

        prompt.append(sourceCode);

        prompt.append(
                "\n```\n"
        );

        /*
         * Tell the AI what kind of response to generate.
         */
        prompt.append(
                "\nReturn:\n"
        );

        prompt.append(
                "1. Summary\n"
        );

        prompt.append(
                "2. Critical issues\n"
        );

        prompt.append(
                "3. Suggested fixes\n"
        );

        prompt.append(
                "4. Overall assessment\n"
        );

        return prompt.toString();
    }
}